### ISSUE TITLE
可以出一个聚宽本地版本吗

### ISSUE THREAD

**Issue by ShuaiLeiLu** [charliedream1/ai_quant_trade#1]
可以出一个聚宽本地版本吗，在网页调试有点不是很方便！谢谢大佬

**Comment by charliedream1** [comment]
目前代码仓egs_strategy已经有一版可以本地运行的版本了。还正在继续完善



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月18日(周一) 晚上7:19
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [charliedream1/ai_quant_trade] 可以出一个聚宽本地版本吗 (Issue #1)




 
可以出一个聚宽本地版本吗，在网页调试有点不是很方便！谢谢大佬

**Comment by ShuaiLeiLu** [comment]
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by ShuaiLeiLu** [comment]
> 代码仓eg_strategy已经有一个版本可以本地运行了。还在继续完善
> […](#)
> ---原始邮件---发件人：***@***.***> 时间：22 年 22 月日（晚上 7 点 19 分）周一 1 月 18 日发送&***@***；抄送：***@***.***>; 主题：[charliedream1/ai_quant_trade] 可以出一个聚宽本地版本吗（Issue #1） 可以出一个聚宽本地版本吗，在网页上调试有点不是很方便！谢谢大佬 — 直接回复此邮件，查看GitHub，或取消订阅。您收到此消息是因为您订阅了此线程。消息 ID：***@***.***>
好的，感谢
