### ISSUE TITLE
咨询量化交易

### ISSUE THREAD

**Issue by zhuangjiaju** [charliedream1/ai_quant_trade#4]
hello 刚才尝试联系您微信，没联系到。
想问下，现在我的需求是： 查询账户、然后查询10档、然后下单，用java实现 ，有没有什么平台是可以支持的么？感恩的心

**Comment by charliedream1** [comment]
看您是像搞自动化实盘交易吧？企业的话可以直接在交易所开户量化接口。个人可以用聚宽，优矿，vnpy,一类



---原始邮件---
发件人: "Jiaju ***@***.***&gt;
发送时间: 2023年4月25日(周二) 中午11:45
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [charliedream1/ai_quant_trade] 咨询量化交易 (Issue #4)




 
hello 刚才尝试联系您微信，没联系到。
 想问下，现在我的需求是： 查询账户、然后查询10档、然后下单，用java实现 ，有没有什么平台是可以支持的么？感恩的心

**Comment by zhuangjiaju** [comment]
聚宽可以java 去调用下单接口？包括查询委托？
然后券商是 浙商的，可以的话我去研究下 感谢



---原始邮件---
发件人: "Optimus ***@***.***&gt;
发送时间: 2023年4月25日(周二) 中午12:07
收件人: ***@***.***&gt;;
抄送: "Jiaju ***@***.******@***.***&gt;;
主题: Re: [charliedream1/ai_quant_trade] 咨询量化交易 (Issue #4)




 看您是像搞自动化实盘交易吧？企业的话可以直接在交易所开户量化接口。个人可以用聚宽，优矿，vnpy,一类 
 
 
 
 ---原始邮件--- 
 发件人: "Jiaju ***@***.***&amp;gt; 
 发送时间: 2023年4月25日(周二) 中午11:45 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.***&amp;gt;; 
 主题: [charliedream1/ai_quant_trade] 咨询量化交易 (Issue #4) 
 
 
 
 
   
 hello 刚才尝试联系您微信，没联系到。 
  想问下，现在我的需求是： 查询账户、然后查询10档、然后下单，用java实现 ，有没有什么平台是可以支持的么？感恩的心

**Comment by charliedream1** [comment]
你可以看看接口文档，一般都是c++和python接口，java估计也支持，你得查查



---原始邮件---
发件人: "Jiaju ***@***.***&gt;
发送时间: 2023年4月25日(周二) 中午12:12
收件人: ***@***.***&gt;;
抄送: "Optimus ***@***.******@***.***&gt;;
主题: Re: [charliedream1/ai_quant_trade] 咨询量化交易 (Issue #4)




 聚宽可以java 去调用下单接口？包括查询委托？ 
 然后券商是 浙商的，可以的话我去研究下 感谢 
 
 
 
 ---原始邮件--- 
 发件人: "Optimus ***@***.***&amp;gt; 
 发送时间: 2023年4月25日(周二) 中午12:07 
 收件人: ***@***.***&amp;gt;; 
 抄送: "Jiaju ***@***.******@***.***&amp;gt;; 
 主题: Re: [charliedream1/ai_quant_trade] 咨询量化交易 (Issue #4) 
 
 
 
 
  看您是像搞自动化实盘交易吧？企业的话可以直接在交易所开户量化接口。个人可以用聚宽，优矿，vnpy,一类  
   
   
   
  ---原始邮件---  
  发件人: "Jiaju ***@***.***&amp;amp;gt;  
  发送时间: 2023年4月25日(周二) 中午11:45  
  收件人: ***@***.***&amp;amp;gt;;  
  抄送: ***@***.***&amp;amp;gt;;  
  主题: [charliedream1/ai_quant_trade] 咨询量化交易 (Issue #4)  
   
   
   
   
     
  hello 刚才尝试联系您微信，没联系到。  
   想问下，现在我的需求是： 查询账户、然后查询10档、然后下单，用java实现 ，有没有什么平台是可以支持的么？感恩的心
